# Generated by Django 5.2.11 on 2026-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockpehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='max_1y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_1y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
